Algoritmo "primeiraAula1"

Var
nome : caractere
idade : inteiro
temFilho : logico
salario : real

Inicio
nome <- "Thiago"
idade <- 24
escreval ("O meu nome é ", nome)
escreval ("Minha idade é de", idade," anos.")

idade <- 45
escreval (idade)

temFilho <- falso
escreval("Tem filho? ", temFilho)

salario <- 460.0154567
escreval(salario:10:2)
//:10 define espaços pra direita na exibicição, :2 espaços à esquerda

Fimalgoritmo